package com.azmiradi.kotlin_base.domain.repository.local.keyValue

import java.lang.reflect.Type


interface StorageKeyValue {
    /**
     * Get secured value is used to decrypt the data after extracting it from local storage using cryptographic key generated by keyAlias.
     *
     * @param storageKey the key which holds the encrypted value.
     * @param keyAlias the value used to get/create crypto key and use it to encrypt the date.
     * @return the encrypted value.
     */
    suspend fun getSecuredValue(storageKey: StorageKey, keyAlias: String): ByteArray

    /**
     * Set secured value is used to encrypt any value before storing in local storage using cryptographic key generated by keyAlias.
     *
     * @param storageKey the key which holds the encrypted value.
     * @param keyAlias the value used to get/create crypto key and use it to encrypt the date.
     */
    suspend fun saveSecuredValue(storageKey: StorageKey, keyAlias: String, value: ByteArray)

    suspend fun getString(storageKey: StorageKey): String
    suspend fun saveString(storageKey: StorageKey, value: String)
    suspend fun clearString(storageKey: StorageKey)

    suspend fun getInt(storageKey: StorageKey): Int?
    suspend fun saveInt(storageKey: StorageKey, value: Int)
    suspend fun clearInt(storageKey: StorageKey)

    suspend fun getBoolean(storageKey: StorageKey): Boolean?
    suspend fun saveBoolean(storageKey: StorageKey, value: Boolean)

    suspend fun <Model> getModelBasedOnType(storageKey: StorageKey, tokenType: Type): Model?
    suspend fun <Model> saveModelBasedOnType(storageKey: StorageKey, value: Model)

    suspend fun hasKey(storageKey: StorageKey): Boolean
    suspend fun clearAllEntries()
}